### ISSUE TITLE
Warning occurring on all sass files: Unknown rule declaration-property-value-disallowed-list , Unknown rule at-rule-disallowed-list

### ISSUE THREAD

**Issue by waldronmatt** [bjankord/stylelint-config-sass-guidelines#111]
![Screenshot_20201109_153459](https://user-images.githubusercontent.com/36429088/98593445-2c1b5580-22a1-11eb-8a7b-7a37bbd2298d.png)

This is my .stylelintrc.js configuration:

```
module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-sass-guidelines",
    "stylelint-config-prettier",
  ],
  plugins: [
    "stylelint-scss",
    "stylelint-order",
  ],
  ignoreFiles: ["dist/**"],
  rules: {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "at-rule-disallowed-list": [],
    "declaration-property-value-disallowed-list": {},
  },
};
```

@bjankord is there any way to disable these last two rules? In my config above I tried setting them to null, false, and assigning empty array/object, but to no success. I'm entirely sure why these errors are cropping up.

https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/index.js#L4

https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/index.js#L21

As far as ordering goes, I tried switching stylelint-config-sass-guidelines above and below stylelint-config-standard to see if there were any conflicts, but still getting the same result. I tried removing everything except stylelint-config-sass-guidelines and the errors are still present.

**Comment by waldronmatt** [comment]
Sorry for opening this up I think this is fixed.

I ended up deleting package-lock.json, node_modules, and upon reinstall of dependencies everything seems to be working fine now.

**Comment by cxspxr** [comment]
Have the very same config, issue still persists after removing node_modules, package-lock.json

**Comment by dmongeau** [comment]
I'm having the same issue for months now. The only thing that fixes the issue is to remove "stylelint-config-sass-guidelines".

**Comment by alexrudd2** [comment]
I had the same issue and found two fixes.

The naive fix is to remove the line containing the rule entirely: https://github.com/bjankord/stylelint-config-sass-guidelines/blob/cbfae2a074dee71f9ca77ac49b576568844377ef/src/.stylelintrc.json#L21-L27
I don't see anything malformed about it, but it does allow keeping the rest of the package intact.

However, in my case I'm using atom with the `linter-stylelint` [package](https://atom.io/packages/linter-stylelint)which appears to be the source of this bug.  See https://github.com/AtomLinter/linter-stylelint/issues/583

I believe the problem is that the `linter-stylelint` is using an old version of `stylelint` itself ([13.3.3](https://github.com/AtomLinter/linter-stylelint/blob/a81cfcd43a374b0df86e955234259598568f6454/package.json#L64)), which gets installed into its local `node_modules`.  **Replacing `~/.atom/packages/linter-stylelint/node_modules/stylelint` with a more modern version (or just deleting it entirely and using a global install) worked for me.**

@cxspxr  and @dmongeau If you're using the atom plugin perhaps this will fix things for you.

**Comment by rgranger** [comment]
I had the same issue when upgrading to version 7.1.0.

Downgrading to 7.0.0 fixes the issue.

**Comment by alexrudd2** [comment]
> I had the same issue when upgrading to version 7.1.0.
> 
> Downgrading to 7.0.0 fixes the issue.

Are you using Atom?  I'm curious if [my fork](https://github.com/alexrudd2/linter-stylelint) of `linter-stylelint` works for you.

**Comment by rgranger** [comment]
> Are you using Atom? I'm curious if my fork of linter-stylelint works for you.

No i'm only using `stylelint` with the CLI
